include:
  - project: 'cicd/gitlab-ci'
    file: 'single/single-pipeline-sbt-gitlab-ci.yaml'

#include:
#  - remote: 'https://git.dar.tech/cicd/gitlab-ci/-/raw/master/single/single-pipeline-gitlab-ci.yaml'
  # project: 'https://git.dar.tech/cicd/gitlab-ci'
  #   ref: master
  #   file: 'single/single-pipeline-gitlab-ci.yaml'


#------------DEV--------------#

repository-dev:
  extends: .repository

sbt-build-dev:
  extends: .sbt-build
  script:
    - "sbt -v -Dsbt.task.timings=true clean compile test dist"

helm-package-dev:
  extends: .helm-package

docker-build-dev:
  extends: .docker-build

deploy-dev:
  extends: .deploy


#-----------QA-------------#

repository:
  extends: .repository
  tags:
    - prod-aws-eu-west
  only:
    refs:
      - qa

sbt-build-qa:
  extends: .sbt-build
  script:
    - "sbt -v -Dsbt.task.timings=true clean compile test dist"
  tags:
    - prod-aws-eu-west
  only:
    refs:
      - qa

helm-package-qa:
  extends: .helm-package
  variables:
    CLUSTER: dev-aws
    ECR_REGION: eu-west-1
  environment:
    name: qa
  tags:
    - prod-aws-eu-west
  only:
    refs:
      - qa

docker-build-qa:
  extends: .docker-build
  variables:
    CLUSTER: dev-aws
    ECR_REGION: eu-west-1
  environment:
    name: qa
  tags:
    - prod-aws-eu-west
  only:
    refs:
      - qa

deploy-qa:
  extends: .deploy
  environment:
    name: qa
  variables:
    CLUSTER: dev-aws
    ECR_REGION: eu-west-1
  tags:
    - prod-aws-eu-west
  only:
    refs:
      - qa

#----------- PRE-PROD -----------#

repository_pre_prod:
  extends: .repository
  only:
    refs:
      - pre-prod

sbt-build-pre-prod:
  extends: .sbt-build
  script:
    - "sbt -v -Dsbt.task.timings=true clean compile test dist"
  only:
    refs:
      - pre-prod

docker-build-pre-prod:
  extends: .docker-build
  variables:
    CLUSTER: pre-prod-aws
    ECR_REGION: eu-west-1
    IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}-pre-prod
  environment:
    name: pre-prod
  only:
    refs:
      - pre-prod

helm-package-pre-prod:
  extends: .helm-package
  variables:
    CLUSTER: pre-prod-aws
    ECR_REGION: eu-west-1
    IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}-pre-prod
  environment:
    name: pre-prod
  only:
    refs:
      - pre-prod

deploy-pre-prod:
  extends: .deploy
  variables:
    ECR_REGION: eu-west-1
    CLUSTER: pre-prod-aws
  environment:
    name: pre-prod
  only:
    refs:
      - pre-prod


#------------ PROD --------------#
repository_prod:
  extends: .repository
  only:
    refs:
      - master
sbt-build-prod:
  extends: .sbt-build
  script:
    - "sbt -v -Dsbt.task.timings=true clean compile test dist"
  only:
    refs:
      - master
docker-build-prod:
  extends: .docker-build
  variables:
    IMAGE_TAG: ${CI_COMMIT_TAG}
  environment:
    name: prod
  only:
    refs:
      - master
helm-package-prod:
  extends: .helm-package
  variables:
    CLUSTER: prod-aws
    IMAGE_TAG: ${CI_COMMIT_TAG}
  environment:
    name: prod
  only:
    refs:
      - master
deploy-prod:
  extends: .deploy
  variables:
    CLUSTER: prod-aws
  environment:
    name: prod
  only:
    refs:
      - master