replicaCount: 1
image:
  repository: REPOSITORY # Managed during pipeline
  tag: IMAGE_TAG   # Managed during pipeline
  pullPolicy: Always

nameOverride: pre-prod-fintel-main-api
fullnameOverride: pre-prod-fintel-main-api

configPath: /config
containerPort: 8080
service:
  type: ClusterIP
  targetPort: 8080
  port: 80

imagePullSecrets: PULL_SECRET # Managed during pipeline

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "ingress"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /api/(.*) /$1 break;
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Context,DNT,X-CustomHeader,X-OwnerContext,X-PerformerContext,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-Authentication-Chain,Source,X-MerchantContext"
    nginx.ingress.kubernetes.io/cors-max-age: "3600"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  path: /api/
  hosts:
    - pre-prod-fintel-api.dar-qa.zone
  tls:
    - secretName: dar-qa-secret
      hosts:
        - pre-prod-fintel-api.dar-qa.zone

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector:
  app: ttmm
tolerations:
  - key: "app"
    operator: "Equal"
    value: "ttmm"
    effect: "NoExecute"

enviroment: pre-prod

env:
  WALLET_QUEUE_SIZE:                           "50"
  WALLET_ENDPOINT:                             "https://pre-prod-fintel-wallet-core.dar-qa.zone"
  WALLET_PREFIX:                               "/api"
  CUSTOMER_QUEUE_SIZE:                         "50"
  CUSTOMER_ENDPOINT:                           "https://pre-prod-fintel-customer-core.dar-qa.zone"
  CUSTOMER_PREFIX:                             "/api"
  DOCUMENT_QUEUE_SIZE:                         "50"
  DOCUMENT_ENDPOINT:                           "https://pre-prod-fintel-api.dar-qa.zone"
  DOCUMENT_PREFIX:                             "/api"
  DOC_PATH:                                    "/root/documents"
  ZEEBE_QUEUE_SIZE:                            "50"
  ZEEBE_ENDPOINT:                              "http://pre-prod-fintel-zeebe-recieve-api.dar-qa.zone/zeebe"
  ZEEBE_PREFIX:                                ""
  NOTIFICATION_QUEUE_SIZE:                     "50"
  NOTIFICATION_ENDPOINT:                       "https://pre-prod-fintel-notification-gateway.dar-qa.zone"
  NOTIFICATION_PREFIX:                         "/api"
  FAQ_QUEUE_SIZE:                              "50"
  FAQ_ENDPOINT:                                "https://pre-prod-fintel-customer-core.dar-qa.zone"
  FAQ_PREFIX:                                  "/api"
  STATISTICS_QUEUE_SIZE:                       "50"
  STATISTICS_ENDPOINT:                         "https://api.binance.com"
  STATISTICS_PREFIX:                           "/api"
  SWAGGER_HOST:                                "pre-prod-fintel-api.dar-qa.zone"
  SWAGGER_SCHEMES:                             "https"
  SERVICE_TIMEOUT:                             "60"
  RECONNECTION_DELAY:                          "60"
  REQUEST_TIMEOUT:                             "60"
  JAVA_OPTS:                                   "-server -Xms256M -Xmx256M"
  LOGBACK:                                     "/root/config/colourful-logback.xml"
  LOG_LEVEL:                                   "INFO"
  TZ:                                          "Asia/Almaty"
  MAIN_URL:                                    "https://pre-prod-fintel-api.dar-qa.zone/api/v1/documents/"
  DOCUMENTS_URL:                               "/root/documents"
  AUTH_JWT_PUBLIC_KEY:                         "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwv6ViO6BYOltGR9RV7H7KporgYEvgSbfMQv9mLn9yE9QFpjKTG1/jqpWnlK/ROQVdoc+jSCh+602XzwY+mPeIo0/kbz1PmakJ4cdqHcTRslfQbHT4fkU6C/FUmPgXZwDrEuKHuab17pefw6K1aqj4jb7FLckFNlm7jMQwdG/VYe58Qat2KVl90YR+KKhtVHGwJKOBCmcl12TBQDppZnI3oaN1b4eepLHyQgJFqNtwyq7h2uz+T7XKDt86sb19ZVNwjfOpexBtE1KvgQu4jVAAvTDNg/lTKlkYu5+fhL9yBnQb6DChkfvw8ikbkmyBbd6rQdN73zz82YGr9iPySklpwIDAQAB"
  AUTH_JWT_ACL_KEY:                            "ttm.wallet"
  REDIS_HOST:                                  "master.pp-ttmm-de1cefd.2dfdbm.euw1.cache.amazonaws.com"
  REDIS_PORT:                                  "6379"
  REDIS_TOKEN:                                 "1NEuM3Ohma74e9d0T"
  REDIS_24H_TICKER_KEY:                        "24h-ticker"
  REDIS_BOOK_TICKER_KEY:                       "book-ticker"
  REDIS_DATABASE:                              "1"
  HASH_KEY:                                    "someKey"
  DELETE_PROFILE_PROCESS_ID:                   "deleteProfile"
  BLOCK_PROFILE_PROCESS_ID:                    "blockProfile"
  TOPUP_PROCESS_ID:                            "topup"
  WITHDRAW_PROCESS_ID:                         "withdraw"
  EXCHANGE_PROCESS_ID:                         "exchange"
  TRANSFER_PROCESS_ID:                         "transfer"
  ELASTIC_HOSTS:                               "10.255.17.100:9200,10.255.80.68:9200,10.255.144.53:9200"
  ELASTIC_CRYPTO_OPERATIONS_INDEX:             "pre-prod-fintel-accounting-crypto-operations"
  AUTH_TEST_CUSTOMER:                          "+70000000001"
  ENV:                                         "pre-prod"
  WHITELIST_AUTHORIZATION_IDS:                 ["cbeef9c3-af59-4a2e-9011-cb76d13b39b5"]
  WHITELIST_AUTHORIZATION_ENABLED:             "false"